# Based on: https://proandroiddev.com/how-to-securely-build-and-sign-your-android-app-with-github-actions-ad5323452ce
name: Build APK

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: |
          echo $NIGHTLY_STORE_FILE
          echo $NIGHTLY_STORE_FILE | base64 -d > KEY_NIGHTLY.jks
          ./gradlew :app:assembleRelease
        env:
          SIGNING_STORE_FILENAME: KEY_NIGHTLY.jks
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          NIGHTLY_STORE_FILE: ${{ secrets.NIGHTLY_STORE_FILE }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: CatholicBible.apk
          path: app/build/outputs/apk/release/*.apk
