# Based on: https://github.com/OpenTracksApp/OpenTracks/blob/main/.github/workflows/build_apk.yml
name: Build APK

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - name: Build with Gradle
        run: |
          echo ${{ secrets.NIGHTLY_STORE_FILE }} | base64 -d > KEY_NIGHTLY.jks
          ./gradlew :app:assembleRelease

        env:
          SIGNING_KEY_FILENAME: KEY_NIGHTLY.jks
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: CatholicBible.apk
          path: build/outputs/apk/release/*.apk
